#include <iostream>
#include <exception>
using namespace std ;

int main(){
    exception ex ;
    return 0 ;
}